<a href="https://colab.research.google.com/github/KaiD888/CS22B_SP26_datafiles/blob/main/m05_hw05_data_explore.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Exploration with Pandas
<table><tr><td>
<img src="https://resizing.flixster.com/Grjhpv0wcwgi-uhfaC3QM8KFglY=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzdmOWE4MWFiLWVlOWMtNDA4Mi05OTA0LTRiNjMxNTEwMzk1MC5qcGc=" height=300><a href="https://resizing.flixster.com/Grjhpv0wcwgi-uhfaC3QM8KFglY=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzdmOWE4MWFiLWVlOWMtNDA4Mi05OTA0LTRiNjMxNTEwMzk1MC5qcGc=">source</a></td><td><img src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRQCHfe9VV3K3Efxv5PYQ_6NYpB20WkKS1zW21UEUmhW1lalECnbwTH3nwQL8XprEMTUCtPeA" height=300><a href="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRQCHfe9VV3K3Efxv5PYQ_6NYpB20WkKS1zW21UEUmhW1lalECnbwTH3nwQL8XprEMTUCtPeA">source</a></td></tr></table>

In [ ]:
# importing the package(s) we want to use
import pandas as pd

### Let's explore the movies data set more! ###
We'll use the `pd.read_csv()` function to read the csv file into a DataFrame.

In [ ]:
csvFile = 'https://raw.githubusercontent.com/csbfx/advpy122-data/master/top_movies_2020.csv'

movies = pd.read_csv(csvFile)
movies.head()

                                Title      Gross  Gross (Adjusted)  Year
0                  Gone with the Wind  200852579        1895421694  1939
1  Star Wars: Episode IV - A New Hope  460998507        1668979715  1977
2                  The Sound of Music  159287539        1335086324  1965
3          E.T. the Extra-Terrestrial  435110554        1329174791  1982
4                             Titanic  659363944        1270101626  1997

### Part 1: Initial data exploration

We can examine the contents of the resultant DataFrame using the `head()` and `tail()` commands:

In [ ]:
### Take a look at the top 3 values of the file
movies.head(3)

                                Title      Gross  Gross (Adjusted)  Year
0                  Gone with the Wind  200852579        1895421694  1939
1  Star Wars: Episode IV - A New Hope  460998507        1668979715  1977
2                  The Sound of Music  159287539        1335086324  1965

In [ ]:
### How about the last 5 values of a the file?
movies.tail(5)

                Title      Gross  Gross (Adjusted)  Year
195            Patton   61749765         373287682  1970
196  Fatal Attraction  156645693         371808159  1987
197        Iron Man 2  312433331         371691971  2010
198          Zootopia  341268248         371109157  2016
199         Liar Liar  181410615         370330510  1997

Use the info() method to get a quick description of the dataframe

In [ ]:
### Get a quick summary of the data using the info() method
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             200 non-null    object
 1   Gross             200 non-null    int64
 2   Gross (Adjusted)  200 non-null    int64
 3   Year              200 non-null    int64
dtypes: int64(3), object(1)
memory usage: 6.4+ KB

### Part 2: Working to filter different elements

2A: Using iloc and loc to extract specific rows and columns

In [ ]:
### Get the first 10 elements (movies) of the second column and convert it into a series with a name
gross_series = movies.iloc[:10,1]
gross_series.name = "Gross"
gross_series

0    200852579
1    460998507
2    159287539
3    435110554
4    659363944
5     65500000
6    260758300
7    111721910
8    232906145
9    184925486
Name: Gross, dtype: int64

In [ ]:
### Get the names of the first 10 movies and convert it into a series and give it type string
titles_movies =  movies.iloc[:10,0].astype(str)
titles_movies.name = "Title"
titles_movies

0                    Gone with the Wind
1    Star Wars: Episode IV - A New Hope
2                    The Sound of Music
3            E.T. the Extra-Terrestrial
4                               Titanic
5                  The Ten Commandments
6                                  Jaws
7                        Doctor Zhivago
8                          The Exorcist
9       Snow White and the Seven Dwarfs
Name: Title, dtype: object

In [ ]:
### Create a smaller dataframe with last 20 elements and all columns except 'Year'. Give the columns new custom names (your choice).
subset = movies.iloc[-20:, :-1].copy()
subset.columns = ["Movie_Title", "Box_Office", "Inflation_Adjusted"]
subset

                                  Movie_Title  Box_Office  Inflation_Adjusted
180                   Guardians of the Galaxy   333176600           385834112
181                                 Furious 7   353007020           384393006
182                       Mission: Impossible   180981856           383664957
183     The Hunger Games: Mockingjay - Part 1   337135885           381611053
184                                   Minions   336045770           381492054
185    Harry Potter and the Half-Blood Prince   302305431           381195025
186                      Saturday Night Fever    94213184           380466039
187                            On Golden Pond   119285432           380274891
188     Austin Powers: The Spy Who Shagged Me   206040086           380038767
189  Harry Potter and the Prisoner of Azkaban   249975996           378596724
190                            Bruce Almighty   242829261           377331774
191                                Funny Girl    52223306           375170115
192                    Mission: Impossible II   215409889           374469239
193                               Rush Hour 2   226164286           374410208
194                                 Apollo 13   173837933           373466649
195                                    Patton    61749765           373287682
196                          Fatal Attraction   156645693           371808159
197                                Iron Man 2   312433331           371691971
198                                  Zootopia   341268248           371109157
199                                 Liar Liar   181410615           370330510

2B: Subsetting the dataframe based on conditions

In [ ]:
### Create a smaller dataframe with movies made in the year 2000s
movies_2000s = movies[(movies["Year"] >= 2000) & (movies["Year"] <= 2009)]
movies_2000s

,Title,Gross,Gross (Adjusted),Year
14,Avatar,760507625,911790952,2009
32,The Dark Knight,535234033,698121220,2008
37,Shrek 2,441226247,665746933,2004
38,Spider-Man,407022860,661768431,2002
52,Pirates of the Caribbean: Dead Man's Chest,423315812,605568108,2006
58,The Lord of the Rings: The Return of the King,377845905,577563989,2003
59,Finding Nemo,380843261,577065505,2003
64,Spider-Man 2,373585825,563687019,2004
68,The Passion of the Christ,370782930,559433976,2004
69,Star Wars: Episode III - Revenge of the Sith,380270577,555871502,2005
71,The Lord of the Rings: The Two Towers,342551365,540886998,2002
79,Harry Potter and the Sorcerer's Stone,318087620,526061784,2001
89,The Lord of the Rings: The Fellowship of the Ring,315544750,513470378,2001
93,Transformers: Revenge of the Fallen,402111870,505051433,2009
99,Star Wars: Episode II - Attack of the Clones,310676740,500999845,2002
109,Pirates of the Caribbean: The Curse of the Bla...,305413918,474580193,2003
114,Monsters Inc.,289916256,462438547,2001
116,Spider-Man 3,336530303,458326991,2007
122,How the Grinch Stole Christmas,260044825,450760716,2000
127,Shrek,267665011,443112922,2001
128,Shrek the Third,322719944,439518590,2007
131,The Matrix Reloaded,281576461,437540583,2003
132,Transformers,319246193,434787677,2007
141,Harry Potter and the Goblet of Fire,290417905,425336158,2005
143,The Chronicles of Narnia: The Lion the Witch a...,291710957,423300994,2005
144,Harry Potter and the Chamber of Secrets,262450136,422965548,2002
145,Pirates of the Caribbean: At World's End,309420425,421405443,2007
147,Iron Man,319034126,415951166,2008
150,Meet the Fockers,279261160,413901010,2004
151,Indiana Jones and the Kingdom of the Crystal S...,317101119,413821365,2008
165,Harry Potter and the Order of the Phoenix,292353413,399669854,2007
174,The Incredibles,261441092,393821100,2004
175,Cast Away,233632142,392548654,2000
179,My Big Fat Greek Wedding,241438208,388100715,2002
185,Harry Potter and the Half-Blood Prince,302305431,381195025,2009
189,Harry Potter and the Prisoner of Azkaban,249975996,378596724,2004
190,Bruce Almighty,242829261,377331774,2003
192,Mission: Impossible II,215409889,374469239,2000
193,Rush Hour 2,226164286,374410208,2001

In [ ]:
### How many movies Gross (use 'Gross (Adjusted)') over 1,500,000,000?
high_gross = movies[movies["Gross (Adjusted)"] > 1_500_000_000]
print(f"Number of movies: {len(high_gross)}")

Number of movies: 2

2C: Customizing the dataframe

In [ ]:
### Use DataFrame.columns to change the column name to 'Movie','Gross', 'Gross_adj', and 'Year'
movies.columns = ["Movie", "Gross", "Gross_adj", "Year"]
movies.head()

                                Movie      Gross   Gross_adj  Year
0                  Gone with the Wind  200852579  1895421694  1939
1  Star Wars: Episode IV - A New Hope  460998507  1668979715  1977
2                  The Sound of Music  159287539  1335086324  1965
3          E.T. the Extra-Terrestrial  435110554  1329174791  1982
4                             Titanic  659363944  1270101626  1997

In [ ]:
### Set the 'Movies' column as the index
movies = movies.set_index("Movie")
movies.head()

                                        Gross   Gross_adj  Year
Movie
Gone with the Wind                  200852579  1895421694  1939
Star Wars: Episode IV - A New Hope  460998507  1668979715  1977
The Sound of Music                  159287539  1335086324  1965
E.T. the Extra-Terrestrial          435110554  1329174791  1982
Titanic                             659363944  1270101626  1997

2D: Getting some statistic about the data

In [ ]:
### Get some statistical information about the 'Gross' column
movies["Gross"].describe()

count    2.000000e+02
mean     2.564920e+08
std      1.705675e+08
min      9.183673e+06
25%      1.169264e+08
50%      2.341963e+08
75%      3.633033e+08
max      9.366622e+08
Name: Gross, dtype: float64

In [ ]:
### What is the average 'Gross (Adjusted)' value for Movies from the 1990s?
avg_90s = movies[(movies["Year"] >= 1990) & (movies["Year"] <= 1999)]["Gross_adj"].mean()
print(f"Avg adjusted gross (1990s): ${avg_90s:,.0f}")

Avg adjusted gross (1990s): $533,060,043

In [ ]:
### What is the standard deviation of 'Gross (Adjusted)'?
std_adj = movies["Gross_adj"].std()
print(f"Std dev of adjusted gross: ${std_adj:,.0f}")

Std dev of adjusted gross: $227,797,683